apiVersion: v1
kind: Service
metadata:
  name: my-k8sphp-svc
  labels:
    app: k8sphp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: k8sphp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8sphp
  labels:
    app: k8sphp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sphp
  template:
    metadata:
      labels:
        app: k8sphp
    spec:
      containers:
      - name: k8sphp
        image: dos174/k8sphp:latest
        ports:
        - containerPort: 80
